export const products = [
  {
    id: 1,
    img: "imgs/Accent-Chair.jpeg",
    name: "Accent Chair",
    price: 25.99,
    company: "Caressa",
  },
  {
    id: 2,
    img: "imgs/Albany-Sectional.jpeg",
    name: "Albany Sectional",
    price: 10.99,
    company: "Ikea",
  },
  {
    id: 3,
    img: "imgs/Albany-Table.jpeg",
    name: "Albany Table",
    price: 79.99,
    company: "Marcos",
  },
  {
    id: 4,
    img: "imgs/Dinning-Table.jpeg",
    name: "Dinning Table",
    price: 6.99,
    company: "Caressa",
  },
  {
    id: 5,
    img: "imgs/Emperor-Bed.jpeg",
    name: "Emperor Bed",
    price: 21.99,
    company: "Liddy",
  },
  {
    id: 6,
    img: "imgs/Entertainment-Center.jpeg",
    name: "Entertainment Center",
    price: 29.99,
    company: "Liddy",
  },
  {
    id: 7,
    img: "imgs/High-Back-Bench.jpeg",
    name: "High-Back Bench",
    price: 9.99,
    company: "Ikea",
  },
  {
    id: 8,
    img: "imgs/Leather-Sofa.jpeg",
    name: "Leather Sofa",
    price: 9.99,
    company: "Liddy",
  },
  {
    id: 9,
    img: "imgs/Modern-Book-Shelf.jpeg",
    name: "Modern Book Shelf",
    price: 8.99,
    company: "Marcos",
  },
  {
    id: 10,
    img: "imgs/Sofa-Set.jpeg",
    name: "Sofa Set",
    price: 69.99,
    company: "Liddy",
  },
  {
    id: 11,
    img: "imgs/Utopia-Sofa.jpeg",
    name: "Utopia Sofa",
    price: 39.99,
    company: "Marcos",
  },
  {
    id: 12,
    img: "imgs/Wooden-Table.jpeg",
    name: "Wooden Table",
    price: 45.99,
    company: "Caressa",
  },
];